import { SubscribeForm } from '@/components/newsletter/SubscribeForm';
import { listNewsletterEditions } from '@/lib/db/newsletter-queries';

export const dynamic = 'force-dynamic';

export default async function NewsletterPage() {
  // Get recent newsletters
  const { items: editions } = await listNewsletterEditions({
    limit: 6,
    status: 'sent',
  });

  return (
    <div className="space-y-12">
      {/* Header */}
      <section className="text-center">
        <h1 className="text-3xl font-semibold tracking-tight text-zinc-950 dark:text-zinc-50">
          Newsletter
        </h1>
        <p className="mx-auto mt-4 max-w-2xl text-sm leading-6 text-zinc-600 dark:text-zinc-300">
          Stay updated with the latest AI news, insights, and analysis. Our curated newsletter
          delivers the most important stories directly to your inbox.
        </p>
      </section>

      {/* Subscribe Form */}
      <section>
        <div className="mx-auto max-w-md">
          <SubscribeForm />
        </div>
      </section>

      {/* Newsletter Archive */}
      {editions.length > 0 && (
        <section className="space-y-6">
          <h2 className="text-xl font-semibold text-zinc-950 dark:text-zinc-50">
            Recent Newsletters
          </h2>
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {editions.map((edition) => (
              <a
                key={edition.id}
                href={`/newsletter/archive/${edition.id}`}
                className="block rounded-xl border border-zinc-200 bg-white p-4 shadow-sm transition hover:shadow-md dark:border-zinc-800 dark:bg-zinc-900"
              >
                <h3 className="font-semibold text-zinc-950 dark:text-zinc-50">{edition.title}</h3>
                {edition.previewText && (
                  <p className="mt-2 text-sm text-zinc-600 dark:text-zinc-400">
                    {edition.previewText}
                  </p>
                )}
                <div className="mt-3 flex items-center justify-between text-xs text-zinc-500">
                  <span>
                    {edition.sentAt ? new Date(edition.sentAt).toLocaleDateString() : 'Draft'}
                  </span>
                  {edition.articleIds.length > 0 && (
                    <span>{edition.articleIds.length} articles</span>
                  )}
                </div>
              </a>
            ))}
          </div>
        </section>
      )}

      {/* Features */}
      <section className="grid gap-8 sm:grid-cols-3">
        <div className="rounded-xl border border-zinc-200 bg-white p-6 dark:border-zinc-800 dark:bg-zinc-900">
          <div className="mb-3 flex h-10 w-10 items-center justify-center rounded-lg bg-zinc-100 dark:bg-zinc-800">
            <svg
              className="h-5 w-5 text-zinc-600 dark:text-zinc-400"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"
              />
            </svg>
          </div>
          <h3 className="font-semibold text-zinc-950 dark:text-zinc-50">Curated Content</h3>
          <p className="mt-2 text-sm text-zinc-600 dark:text-zinc-400">
            Hand-picked articles from the best sources in AI and technology.
          </p>
        </div>

        <div className="rounded-xl border border-zinc-200 bg-white p-6 dark:border-zinc-800 dark:bg-zinc-900">
          <div className="mb-3 flex h-10 w-10 items-center justify-center rounded-lg bg-zinc-100 dark:bg-zinc-800">
            <svg
              className="h-5 w-5 text-zinc-600 dark:text-zinc-400"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M13 10V3L4 14h7v7l9-11h-7z"
              />
            </svg>
          </div>
          <h3 className="font-semibold text-zinc-950 dark:text-zinc-50">AI-Powered Analysis</h3>
          <p className="mt-2 text-sm text-zinc-600 dark:text-zinc-400">
            Summaries and key insights generated by advanced AI models.
          </p>
        </div>

        <div className="rounded-xl border border-zinc-200 bg-white p-6 dark:border-zinc-800 dark:bg-zinc-900">
          <div className="mb-3 flex h-10 w-10 items-center justify-center rounded-lg bg-zinc-100 dark:bg-zinc-800">
            <svg
              className="h-5 w-5 text-zinc-600 dark:text-zinc-400"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"
              />
            </svg>
          </div>
          <h3 className="font-semibold text-zinc-950 dark:text-zinc-50">Your Schedule</h3>
          <p className="mt-2 text-sm text-zinc-600 dark:text-zinc-400">
            Choose daily, weekly, or biweekly delivery based on your preferences.
          </p>
        </div>
      </section>
    </div>
  );
}
